algorithm: main
save_dir: ./saved_models/classic_cv
save_name: main_jhc_110_0
resume: False
load_path: ./saved_models/classic_cv/softmatch_cifar10_40_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 128
num_train_iter: 12288
num_eval_iter: 32
num_log_iter: 32
num_labels: 110
batch_size: 16
eval_batch_size: 16
hard_label: True
T: 0.5
use_quantile: False
clip_thresh: False
proj_size: 64
k: 20
use_mix: True
use_contrast: True
contrast_use_ulb: False
contrast_threshold: 0.2
contrast_T: 0.2
bank_size: 256
per_class: False
ema_p: 0.999
ent_loss_ratio: 0.001
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.01
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet50
net_from_name: False
data_dir: /home/ubuntu/wwc/dataset/jhu_crowd_v2.0/train
test_data_dir: /home/ubuntu/wwc/dataset/jhu_crowd_v2.0/test
dataset: jhc
train_sampler: RandomSampler
num_classes: 3
num_workers: 10
seed: 3
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10072
dist_backend: nccl
gpu: 0
